### ISSUE TITLE
format of the env files

### ISSUE THREAD

**Issue by rordi** [websanova/vue-env#3]
Here is the expected format of the .env file and the local, staging, production etc. files. It's not mentioned in the readme / documentation.

.env
```
module.exports = {
  APP_ENV: 'local',
}
```

local.js etc.
```
module.exports = {
  DEBUG: true,
  APP_ENV: 'local',
  API_URL: 'http://localhost/api/',
  // more env vars here 
}
```

**Comment by websanova** [comment]
So it looks for a .env in the root. It's a js file but it should just be named like that. This is just for deployment services which usually only have this file available for editing.

Theo there files can go into src/env where you can store default values for each environment.

Also note that if you run into any issues just check the source it's only few lines of code.

https://github.com/websanova/vue-env/blob/master/src/index.js
