### ISSUE TITLE
ERR These relative modules were not found

### ISSUE THREAD

**Issue by gandra** [websanova/vue-env#4]
I have installed plugin with

`npm install @websanova/vue-env`

and then put this code into main file:

`Vue.use(require('@websanova/vue-env'))`

after starting app I am getting following error:

```
 WARNING  Compiled with 2 warnings10:08:17

These relative modules were not found:

* ../../../../.env in ./~/@websanova/vue-env/src/index.js
* ../../../../src/env in ./~/@websanova/vue-env/src/index.js
```

Environment info:

```
$ npm ls vue
cir-web@1.0.0 C:\Work\Trezor\src-crf\cir-web
+-- bootstrap-vue@0.18.0
| `-- vue@2.4.1  deduped
+-- vue@2.4.1
`-- vue-tables-2@0.6.53
  +-- vue@2.4.1  deduped
  `-- vue-pagination-2@0.3.2
    `-- vue@2.4.1  deduped

```

```
$ npm -v
5.3.0
```

**Comment by websanova** [comment]
Ah ya, it's looking for a `.env` in the root. I will put a silent ignore
for this with a warning instead. Note that the `.env` is treated as a joke
file.

**Comment by websanova** [comment]
Actually I just checked the source, this should already be caught, what version are you using?

**Comment by michaelbukachi** [comment]
Is there any way to disable the warning?
