### ISSUE TITLE
example.env

### ISSUE THREAD

**Issue by designbyadrian** [websanova/vue-env#5]
I can figure out what the env file should look like by reading the source code, but it'd be better to supply an example.env file so I don't have to.

**Comment by websanova** [comment]
There is kind default values. Just whatever you want in your app.

**Comment by pag6606** [comment]
I have the same problem, then I solve using having this in my production.js file 
` module.exports.var = "value"`
Then I call using in the vue file
`this.$env.data.var`
Hope this help

**Comment by websanova** [comment]
It's just a .env file in json format. NOthing special.
