### ISSUE TITLE
Can't get ENV vars

### ISSUE THREAD

**Issue by niko-afv** [websanova/vue-env#6]
Hi, i get this in my root/src/main.js
`Vue.use(require('@websanova/vue-env'));`
`console.log("Api url: "+Vue.env.get("api_url"));`

in my root/.env i have this
`APP_ENV=local`

in my root/src/env/local.js i have this
`module.exports.api_url = "api_url"`

but in console i see that:
`Api url: undefined`

what am I doing wrong??

**Comment by websanova** [comment]
The  .env file is JSON format
