### ISSUE TITLE
Vue is not defined

### ISSUE THREAD

**Issue by lefuturiste** [websanova/vue-env#8]
ReferenceError: Vue is not defined[Learn More]

app.js%20line%20740%20%3E%20eval:19:13
_merge
index.js:19
Env
index.js:29
install
index.js:48
initUse/Vue.use
vue.esm.js:4683
<anonymous>
main.js:12
./src/main.js
http://localhost:8080/app.js:1118:1
__webpack_require__
http://localhost:8080/app.js:679:12
fn
http://localhost:8080/app.js:89:20
[0]
http://localhost:8080/app.js:1135:18
__webpack_require__
http://localhost:8080/app.js:679:12
<anonymous>
http://localhost:8080/app.js:725:18
<anonymous>
http://localhost:8080/app.js:1:11

**Comment by BalaWxd** [comment]
I got similar issue which seems to be an exception from vue-dot package. So I did is to create a `window.Vue = Vue` solved my problem.

**Comment by azanona** [comment]
@BalaWxd can you explain where fix?
thanks.

**Comment by websanova** [comment]
Where are you using? How are you including Vue, it should be there as long as you have vue installed before using vue-env.

**Comment by lefuturiste** [comment]
Problem solved, my mistake
